@startuml
start
:User executes add command for a tutor;
:Parse command arguments;

if () then ([Invalid input/s])
    :Throw \nParseException;
    stop
else ([Valid input/s])
    :Create a Tutor object as pass \n it as well as the PersonType \n into an Add command;

endif
    :Execute Add command;
    :Update tutor list in Model;
    :Return CommandResult;
stop
@enduml