@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-down-> "1" UniqueTutorList
AddressBook *-down-> "1" UniqueStudentList
AddressBook *-right-> "1" UniqueTagList

UniqueTutorList -down-> "*" Tutor
UniqueStudentList -down-> "*" Student
UniqueTagList -[hidden]down- UniqueTutorList
UniqueTagList -[hidden]down- UniqueStudentList
UniqueTagList *-right-> "*" Tag

Tutor *-up-> "1..*" Tag

Tutor *--> "1" Name
Tutor *--> "1" Phone
Tutor *--> "1" Gender
Tutor *--> "1" Qualification

Tutor -[hidden]right-> Student

Student *-up-> "1..*" Tag

Student *--> "1" Name
Student *--> "1" Phone
Student *--> "1" Gender
@enduml
