@startuml
start
:User enters edit tutor command;
:Parse command arguments;

if () then ([input is valid])
    :Create new tutor and populate
    with edited details if present;
    if () then ([new tutor details are different])
        :Replace original tutor in
        tutor list with edited tutor;
        :Display success message;
        stop
    else ([else])
        :Throw CommandException;
        stop
    endif
else ([else])
    :Throw ParseException;
    stop
endif
@enduml
