@startuml
start
:User executes edit command;
:EditCommandParser parses command arguments;

if () then ([Valid input])
    if () then([Edit tutor])
        :Create EditTutorDescriptor;
        :Populate EditTutorDescriptor
        with edited details if present;
        :Create edited Tutor
        from EditTutorDescriptor;
        :Replace edited
        Tutor in Model;
    else ([Edit student])
        :Create EditStudentDescriptor;
        :Populate EditStudentDescriptor
        with edited details if present;
        :Create edited Student
        from EditStudentDescriptor;
        :Replace edited
        Student in Model;
    endif
else ([else])
    :Throw ParseException;
    stop
endif
stop
@enduml
