@startuml
start
:User executes filter command;
:Parse command arguments;

if () then ([input is valid])
    :Execute Filter command;
    :Update matched tutor list;
    :Display the list of filtered tutors;
    stop
else ([else])
    :Throw \nParseException;
stop
@enduml
