@startuml
start
:User enters find command;
:Parse command arguments;

if () then ([Invalid input/s])
    :Throw \nParseException;
else ([Valid input/s])
    :Create and chain predicates related
    to prefix/s specified in input;
    :Execute Find command;
    :Update student list in Model;
    :Return CommandResult;

endif

stop
@enduml
