@startuml
start
:User executes list command for the student list;
:Parse command arguments;

if () then ([Invalid input/s])
    :Throw \nParseException;
    stop
else ([Valid input/s])
    :Create a list command that\nshows the list of all students;

endif
    :Execute List command;
    :Return CommandResult;
stop
@enduml
