@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant "l:ListCommand" as ListCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute\n("list s")
activate LogicManager
LogicManager -> AddressBookParser : parseCommand\n("list s")
activate AddressBookParser

create ListCommandParser
AddressBookParser -> ListCommandParser
activate ListCommandParser

AddressBookParser <-- ListCommandParser
deactivate ListCommandParser

AddressBookParser -> ListCommandParser : parse(" s")
activate ListCommandParser

create ListCommand
ListCommandParser -> ListCommand
activate ListCommand

ListCommandParser <-- ListCommand : l
deactivate ListCommand

ListCommandParser --> AddressBookParser : l
deactivate ListCommandParser

AddressBookParser --> LogicManager : l
deactivate AddressBookParser
destroy ListCommandParser

LogicManager -> ListCommand : execute(model)
activate ListCommand

ListCommand -> Model : updateFilteredTutorList\n(PREDICATE_SHOW_ALL_TUTORS);
activate Model
ListCommand <-- Model
deactivate Model

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult --> ListCommand
deactivate CommandResult

ListCommand --> LogicManager : commandResult
deactivate ListCommand

[<--LogicManager : commandResult
ListCommand -[hidden]-> LogicManager
destroy ListCommand
deactivate LogicManager
@enduml