@startuml
start
:User executes list command for the student list;
:Parse command arguments;

if () then ([input is valid])
    :Create a list command that\nshows the list of all students;
    :Execute List command;
    :Displays all the students;
    stop
else ([else])
    :Throw ParseException;
stop
@enduml
