@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBook LOGIC_COLOR
participant ":MatchCommandParser" as MatchCommandParser LOGIC_COLOR
participant ":MatchCommand" as MatchCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "p:TagsContainsTagPredicate" as TagPredicate MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("match 1")
activate LogicManager

LogicManager -> AddressBook : parseCommand("match 1")
activate AddressBook
create MatchCommandParser
AddressBook -> MatchCommandParser
activate MatchCommandParser

MatchCommandParser --> AddressBook
deactivate MatchCommandParser

AddressBook -> MatchCommandParser : parse(" 1")
activate MatchCommandParser
create MatchCommand
MatchCommandParser -> MatchCommand
activate MatchCommand
MatchCommand --> MatchCommandParser
deactivate MatchCommand

MatchCommandParser --> AddressBook
deactivate MatchCommandParser
MatchCommandParser -[hidden]-> AddressBook : result
destroy MatchCommandParser

AddressBook --> LogicManager
deactivate AddressBook

LogicManager -> MatchCommand : execute(model)
activate MatchCommand

create TagPredicate
MatchCommand -> TagPredicate
activate TagPredicate
TagPredicate --> MatchCommand
deactivate TagPredicate

MatchCommand -> Model : updateMatchedTutor(p)
activate Model
Model --> MatchCommand
deactivate Model

MatchCommand --> LogicManager : result
deactivate MatchCommand
MatchCommand -[hidden]-> LogicManager : result
destroy MatchCommand

[<--LogicManager
deactivate LogicManager
@enduml
