@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueStudentList
Class UniqueTutorList
Class Qualification
Class Gender
Class Student
Class Tutor
Class Name
Class Phone
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -down-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student
Student *--> Name
Student *--> Phone
Student *--> Gender
Student *-up-> "1..*" Tag

AddressBook *--> "1" UniqueTutorList
UniqueTutorList --> "~* all" Tutor
Tutor *--> Name
Tutor *--> Phone
Tutor *--> Gender
Tutor *--> Qualification
Tutor *-up-> "1..*" Tag

Tutor -[hidden]right-> Student
Name -[hidden]right-> Phone
Phone -[hidden]right-> Gender
Gender -[hidden]right-> Qualification

ModelManager -->"~* filtered" Tutor
ModelManager -->"~* filtered" Student
@enduml
