@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>

Class StorageManager
package "CliTutors Storage" #F4F6F6{
Interface CliTutorsStorage <<Interface>>
Class JsonCliTutorsStorage
Class JsonSerializableCliTutors
Class "{abstract}\nJsonAdaptedPerson" as Person
Class JsonAdaptedStudent extends Person
Class JsonAdaptedTutor extends Person
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" CliTutorsStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> CliTutorsStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonCliTutorsStorage .up.|> CliTutorsStorage
JsonCliTutorsStorage ..> JsonSerializableCliTutors
JsonSerializableCliTutors --> "*" Person
Person --> "*" JsonAdaptedTag

@enduml
