@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CliTutorsParser" as CliTutorsParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedCliTutors" as VersionedCliTutors MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> CliTutorsParser : parseCommand(undo)
activate CliTutorsParser

create UndoCommand
CliTutorsParser -> UndoCommand
activate UndoCommand

UndoCommand --> CliTutorsParser
deactivate UndoCommand

CliTutorsParser --> LogicManager : u
deactivate CliTutorsParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoCliTutors()
activate Model

Model -> VersionedCliTutors : undo()
activate VersionedCliTutors

VersionedCliTutors -> VersionedCliTutors :resetData(ReadOnlyCliTutors)
VersionedCliTutors --> Model :
deactivate VersionedCliTutors

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
